### PR TITLE
Implement Sync Todoist -> Obsidian

### PR DESCRIPTION
**Pull request by Heiss**
This is the follow up PR for #66 

Tasks:
- [x] Create tasks in obsidian
  - [x] add tags from todoist
  - [x] add due date from todoist
  - [x] add notes as intended bullet points from todoist
  - [x] plugin needs to write back the link to the new task
  - [x] create setting for disable link update
  - [x] respect due date with time
- [ ] sync description from obsidian to todoist (maybe separate PR?)
  - all intended bullet points which are non tasks should be the description
  - one bullet point is a paragraph, maybe?
- [x] Sync tags from todoist->obsidian
  - [x] first tryout of a working synchronization
  - [x] Use another REST API Endpoint for task tags update [more informations](https://github.com/HeroBlackInk/ultimate-todoist-sync-for-obsidian/pull/67#issuecomment-1795411370) (instead of full tasks sync endpoint!)
- [x] rewrite tags sync todoist->obsidian to make it more reliable when changes are made on both ends
  - how we can find out, if there are changes in obsidian still pending to publish to todoist, so they do not get deleted, when trying to get updated tags from todoist
- [x] add an exception list for tags, so they are stripped away, also when new option to leave text in place in content.
- [x] update README.md
- [x] update CHANGELOG.md
- [ ] add an option to trigger a rewrite to todoist from obsidian (overwrite comments etc.)
  - this would help in case, the plugin makes an error
- [ ] refactor code
  - [ ] remove duplicate code
  - [ ] add comments
  - [ ] check for API calls and how to reduce them
- [ ] if a task was created intended below another task, it will be synced to todoist as a subtask, but it does not get liftet as task, if you remove the intendation, which results in weird behaviour.
  - it creates a new task in first-level, but updates also the text from todoist back in place
- [ ] testing, testing, testing...

Bugs:
- [ ] if you type your task, the plugin sometimes write the tag while typing and this disturbs the flow
  - it should wait or only writes, if the cursor is not on this line anymore

Outside of this PR scope
- Automatically create a simple default template to simplify setup.
- if you move task in todoist to a different project, it will not be synced to obsidian
  - in sync API there is no event for this, same way as label changes... so the plugin cannot sync them without a full sync
  - does not need to be implemented here, because there is currently no way to specify this inside of a note
- handle rate limit from todoist, instead of flooding the API

### CODE REVIEW

**Comment by Heiss** [comment]
For documentation, i copied your comment from [here](https://github.com/HeroBlackInk/ultimate-todoist-sync-for-obsidian/pull/66#issuecomment-1795066439):

> Due to rate limits, each user is allowed to make a maximum of 45 full sync requests within a 15-minute period. It is recommended to utilize the REST API's '**Get active tasks**' feature, which allows a maximum of 450 REST API requests per user within the same 15-minute timeframe.
> 
> ```
> import { TodoistApi } from "@doist/todoist-api-typescript"
> 
> const api = new TodoistApi("0123456789abcdef0123456789")
> 
> api.getTasks()
>     .then((tasks) => console.log(tasks))
>     .catch((error) => console.log(error))
> ```
> 
> Example response:
> 
> > [
> > {
> > creatorId: "2671355",
> > createdAt: "2019-12-11T22:36:50.000000Z",
> > assigneeId: "2671362",
> > assignerId: "2671355",
> > commentCount: 10,
> > isCompleted: false,
> > content: "Buy Milk",
> > description: "",
> > due: {
> > date: "2016-09-01",
> > isRecurring: false,
> > datetime: "2016-09-01T09:00:00.000000Z",
> > string: "tomorrow at 12",
> > timezone: "Europe/Moscow"
> > },
> > "duration": null,
> > id: "2995104339",
> > labels: ["Food", "Shopping"],
> > order: 1,
> > priority: 1,
> > projectId: "2203306141",
> > sectionId: "7025",
> > parentId: "2995104589",
> > url: "https://todoist.com/showTask?id=2995104339"
> > }
> > ]
> 
> Returns a JSON-encoded array containing all active tasks.

**Comment by HeroBlackInk** [comment]
I am a severe procrastinator, so I tend to be slower in everything I do. Please don't mind.

**Comment by HeroBlackInk** [comment]
Regarding bidirectional sync, I have used a lock mechanism where it checks if there is an ongoing sync task before each sync, and if there is, it prevents the current sync from executing. This method was also used for the reverse synchronization of content and dates, and so far, I haven't encountered any issues.

**Comment by HeroBlackInk** [comment]
I understand what you mean. Because there is no event notification for label updates, the only way to handle the issue of tag synchronization is to rely on the Incremental sync API. However, I haven't finished working on this module yet.

**Comment by HeroBlackInk** [comment]
> Incremental sync
> 
> The Sync API allows clients to retrieve only updated resources, and this is done by using the sync_token in your Sync API request.


[https://developer.todoist.com/sync/v8/#read-resources](url)

**Comment by Heiss** [comment]
> > Incremental sync
> > The Sync API allows clients to retrieve only updated resources, and this is done by using the sync_token in your Sync API request.
> 
> [https://developer.todoist.com/sync/v8/#read-resources](url)

Mh. Using the sync_token with sync seems to work great, but if you change the label / tag, it does not come up with the task again. Only description / content seems to trigger an "update" event, so you do not see it... Only a full sync or a change in content / description / project / etc. would trigger a tag sync. :(

**Comment by HeroBlackInk** [comment]
> > > Incremental sync
> > > The Sync API allows clients to retrieve only updated resources, and this is done by using the sync_token in your Sync API request.
> > 
> > 
> > [https://developer.todoist.com/sync/v8/#read-resources](url)
> 
> Mh. Using the sync_token with sync seems to work great, but if you change the label / tag, it does not come up with the task again. Only description / content seems to trigger an "update" event, so you do not see it... AFAIK Only a full sync or a change in content / description / project / etc. would trigger a tag sync. :(

I am sorry, I haven't tested this API before, it seems like my idea is wrong.

**Comment by Heiss** [comment]
So... After some weeks, i had time today to continue my journey with obsidian plugin :)

i think, my additions fixes #71 too. 

Now, i need some time to do some cleanup and prettify the code. Currently, it is a mess in multiple places and is not KISS.
But everything should be tested a lot! In my testing environemnt, it works great and as expected.

After the cleanup, i will install my changes in my production environment and test it a few days. But i do not know, when i have time to do this.

Because i have no other way to find out updates on todoist in some topics (e.g. for dueDate or labels), i assume that if there are changes on todoist side, these are the current ones. If someone changes on obsidian side, it will be checked by your existing code automatically and pushed to todoist ASAP. So there should be no need of strict update algorithm. But this breaks, if someone switches between todoist and obsidian between two synchronizations...

**Comment by HeroBlackInk** [comment]
I'm sorry, but I have been feeling quite terrible lately. I've been struggling to accomplish even simple tasks without someone to keep me on track. If you know how to release a new version, you can simply merge it into the main branch and publish the updated version.

**Comment by HeroBlackInk** [comment]
How to Publish a New Release:

Step 1: Update version in 'manifest.json', and push it to the main branch."
```
git commit -am "new release"
git push origin master
```

step 2: release new version
```
git tag -a 1.0.44 -m "1.0.44"
git push origin 1.0.44
```

**Comment by HeroBlackInk** [comment]
Thans!

I am facing difficulties managing my time, and everything seems to be in a state of chaos.

**Comment by Druzco** [comment]
Looks really promising!

**Comment by solace** [comment]
Thank you both for your hard work with this and I hope you have some time to look after yourselves as well.

**Comment by Suyashtnt** [comment]
How stable is this to use? Also, hope stuff gets better for you @HeroBlackInk.

**Pull request closed without merging**
